"""
locations.py
-------------
Fixed state -> city list used by Lead Finder's location dropdowns.

This is the single source of truth for every location a search can be
run against. Because every entry here is an exact "City, ST" string
that OpenStreetMap/Nominatim can resolve cleanly, picking from these
dropdowns instead of free-typing a location means:
  - no more accidentally searching an entire state (which is what
    caused the timeout on a bare "florida" search)
  - no more misspelled or ambiguous city names
  - every search sent to Nominatim is in a shape it resolves reliably

STATE_CITIES maps a full state name to a sorted list of its cities,
each written as "City, ST" exactly as OpenStreetMap expects it.
STATE_ABBR maps each full state name to its two-letter abbreviation,
in case the UI ever needs it separately from the city strings.
"""

STATE_CITIES = {
    "Alabama": [
        "Abbeville, AL",
        "Adamsville, AL",
        "Alabaster, AL",
        "Albertville, AL",
        "Alexander City, AL",
        "Andalusia, AL",
        "Anniston, AL",
        "Arab, AL",
        "Athens, AL",
        "Atmore, AL",
        "Auburn, AL",
        "Bessemer, AL",
        "Birmingham, AL",
        "Boaz, AL",
        "Cullman, AL",
        "Decatur, AL",
        "Dothan, AL",
        "Enterprise, AL",
        "Eufaula, AL",
        "Florence, AL",
        "Fort Payne, AL",
        "Gadsden, AL",
        "Greenville, AL",
        "Guntersville, AL",
        "Huntsville, AL",
        "Jasper, AL",
        "Mobile, AL",
        "Montgomery, AL",
        "Opelika, AL",
        "Oxford, AL",
        "Phenix City, AL",
        "Prattville, AL",
        "Selma, AL",
        "Talladega, AL",
        "Tuscaloosa, AL",
        "Tuskegee, AL",
    ],
    "Alaska": [
        "Anchorage, AK",
        "Badger, AK",
        "Bethel, AK",
        "College, AK",
        "Fairbanks, AK",
        "Homer, AK",
        "Juneau, AK",
        "Kenai, AK",
        "Ketchikan, AK",
        "Kodiak, AK",
        "Nome, AK",
        "North Pole, AK",
        "Palmer, AK",
        "Sitka, AK",
        "Soldotna, AK",
        "Wasilla, AK",
    ],
    "Arizona": [
        "Apache Junction, AZ",
        "Avondale, AZ",
        "Buckeye, AZ",
        "Bullhead City, AZ",
        "Casa Grande, AZ",
        "Chandler, AZ",
        "Flagstaff, AZ",
        "Fountain Hills, AZ",
        "Gilbert, AZ",
        "Glendale, AZ",
        "Goodyear, AZ",
        "Kingman, AZ",
        "Lake Havasu City, AZ",
        "Marana, AZ",
        "Maricopa, AZ",
        "Mesa, AZ",
        "Nogales, AZ",
        "Oro Valley, AZ",
        "Page, AZ",
        "Peoria, AZ",
        "Phoenix, AZ",
        "Prescott, AZ",
        "Queen Creek, AZ",
        "Sahuarita, AZ",
        "Scottsdale, AZ",
        "Sierra Vista, AZ",
        "Surprise, AZ",
        "Tempe, AZ",
        "Tucson, AZ",
        "Yuma, AZ",
    ],
    "Arkansas": [
        "Arkadelphia, AR",
        "Batesville, AR",
        "Benton, AR",
        "Bentonville, AR",
        "Cabot, AR",
        "Camden, AR",
        "Conway, AR",
        "El Dorado, AR",
        "Fayetteville, AR",
        "Forrest City, AR",
        "Fort Smith, AR",
        "Hot Springs, AR",
        "Jacksonville, AR",
        "Jonesboro, AR",
        "Little Rock, AR",
        "Maumelle, AR",
        "Mountain Home, AR",
        "Paragould, AR",
        "Pine Bluff, AR",
        "Russellville, AR",
        "Searcy, AR",
        "Sherwood, AR",
        "Springdale, AR",
        "Texarkana, AR",
        "West Memphis, AR",
    ],
    "California": [
        "Anaheim, CA",
        "Antioch, CA",
        "Bakersfield, CA",
        "Berkeley, CA",
        "Burbank, CA",
        "Chico, CA",
        "Chula Vista, CA",
        "Clovis, CA",
        "Concord, CA",
        "Corona, CA",
        "Costa Mesa, CA",
        "Daly City, CA",
        "Downey, CA",
        "El Cajon, CA",
        "El Monte, CA",
        "Escondido, CA",
        "Fairfield, CA",
        "Fontana, CA",
        "Fremont, CA",
        "Fresno, CA",
        "Fullerton, CA",
        "Garden Grove, CA",
        "Glendale, CA",
        "Hayward, CA",
        "Huntington Beach, CA",
        "Inglewood, CA",
        "Irvine, CA",
        "Lancaster, CA",
        "Long Beach, CA",
        "Los Angeles, CA",
        "Modesto, CA",
        "Moreno Valley, CA",
        "Murrieta, CA",
        "Norwalk, CA",
        "Oakland, CA",
        "Oceanside, CA",
        "Ontario, CA",
        "Orange, CA",
        "Oxnard, CA",
        "Palmdale, CA",
        "Pasadena, CA",
        "Pomona, CA",
        "Rancho Cucamonga, CA",
        "Redding, CA",
        "Rialto, CA",
        "Richmond, CA",
        "Riverside, CA",
        "Roseville, CA",
        "Sacramento, CA",
        "Salinas, CA",
        "San Bernardino, CA",
        "San Diego, CA",
        "San Francisco, CA",
        "San Jose, CA",
        "San Leandro, CA",
        "San Mateo, CA",
        "Santa Ana, CA",
        "Santa Barbara, CA",
        "Santa Clara, CA",
        "Santa Clarita, CA",
        "Santa Maria, CA",
        "Santa Monica, CA",
        "Santa Rosa, CA",
        "Simi Valley, CA",
        "Stockton, CA",
        "Sunnyvale, CA",
        "Temecula, CA",
        "Thousand Oaks, CA",
        "Torrance, CA",
        "Vallejo, CA",
        "Victorville, CA",
        "Visalia, CA",
        "West Covina, CA",
        "Westminster, CA",
        "Whittier, CA",
    ],
    "Colorado": [
        "Arvada, CO",
        "Aurora, CO",
        "Boulder, CO",
        "Brighton, CO",
        "Broomfield, CO",
        "Castle Rock, CO",
        "Centennial, CO",
        "Colorado Springs, CO",
        "Commerce City, CO",
        "Denver, CO",
        "Durango, CO",
        "Englewood, CO",
        "Erie, CO",
        "Fort Collins, CO",
        "Golden, CO",
        "Grand Junction, CO",
        "Greeley, CO",
        "Highlands Ranch, CO",
        "Johnstown, CO",
        "Lakewood, CO",
        "Littleton, CO",
        "Longmont, CO",
        "Loveland, CO",
        "Montrose, CO",
        "Parker, CO",
        "Pueblo, CO",
        "Thornton, CO",
        "Westminster, CO",
        "Wheat Ridge, CO",
    ],
    "Connecticut": [
        "Bridgeport, CT",
        "Bristol, CT",
        "Danbury, CT",
        "East Hartford, CT",
        "Greenwich, CT",
        "Hamden, CT",
        "Hartford, CT",
        "Manchester, CT",
        "Meriden, CT",
        "Milford, CT",
        "New Britain, CT",
        "New Haven, CT",
        "Norwalk, CT",
        "Norwich, CT",
        "Shelton, CT",
        "Stamford, CT",
        "Stratford, CT",
        "Torrington, CT",
        "Waterbury, CT",
        "West Hartford, CT",
        "West Haven, CT",
    ],
    "Delaware": [
        "Dover, DE",
        "Middletown, DE",
        "Newark, DE",
        "New Castle, DE",
        "Seaford, DE",
        "Smyrna, DE",
        "Wilmington, DE",
    ],
    "Florida": [
        "Altamonte Springs, FL",
        "Apopka, FL",
        "Boca Raton, FL",
        "Bonita Springs, FL",
        "Boynton Beach, FL",
        "Bradenton, FL",
        "Cape Coral, FL",
        "Clearwater, FL",
        "Clermont, FL",
        "Coconut Creek, FL",
        "Coral Gables, FL",
        "Coral Springs, FL",
        "Daytona Beach, FL",
        "Deerfield Beach, FL",
        "Delray Beach, FL",
        "Deltona, FL",
        "Doral, FL",
        "Fort Lauderdale, FL",
        "Fort Myers, FL",
        "Gainesville, FL",
        "Hialeah, FL",
        "Hollywood, FL",
        "Homestead, FL",
        "Jacksonville, FL",
        "Jupiter, FL",
        "Kissimmee, FL",
        "Lakeland, FL",
        "Largo, FL",
        "Lauderhill, FL",
        "Melbourne, FL",
        "Miami, FL",
        "Miami Beach, FL",
        "Miami Gardens, FL",
        "Miramar, FL",
        "Naples, FL",
        "Ocala, FL",
        "Orlando, FL",
        "Palm Bay, FL",
        "Palm Beach Gardens, FL",
        "Palm Coast, FL",
        "Pembroke Pines, FL",
        "Pensacola, FL",
        "Plant City, FL",
        "Plantation, FL",
        "Pompano Beach, FL",
        "Port St. Lucie, FL",
        "Sarasota, FL",
        "St. Augustine, FL",
        "St. Petersburg, FL",
        "Sunrise, FL",
        "Tallahassee, FL",
        "Tamarac, FL",
        "Tampa, FL",
        "Titusville, FL",
        "Venice, FL",
        "West Palm Beach, FL",
        "Wesley Chapel, FL",
        "Winter Garden, FL",
        "Winter Haven, FL",
        "Winter Park, FL",
    ],
    "Georgia": [
        "Albany, GA",
        "Alpharetta, GA",
        "Athens, GA",
        "Atlanta, GA",
        "Augusta, GA",
        "Brunswick, GA",
        "Columbus, GA",
        "Dalton, GA",
        "Duluth, GA",
        "Gainesville, GA",
        "Johns Creek, GA",
        "Kennesaw, GA",
        "Lawrenceville, GA",
        "Macon, GA",
        "Marietta, GA",
        "McDonough, GA",
        "Newnan, GA",
        "Roswell, GA",
        "Rome, GA",
        "Savannah, GA",
        "Smyrna, GA",
        "Statesboro, GA",
        "Stockbridge, GA",
        "Valdosta, GA",
        "Warner Robins, GA",
    ],
    "Hawaii": [
        "Hilo, HI",
        "Honolulu, HI",
        "Kahului, HI",
        "Kailua, HI",
        "Kaneohe, HI",
        "Kapolei, HI",
        "Kihei, HI",
        "Lahaina, HI",
        "Pearl City, HI",
        "Waianae, HI",
        "Waipahu, HI",
    ],
    "Idaho": [
        "Boise, ID",
        "Caldwell, ID",
        "Coeur d'Alene, ID",
        "Eagle, ID",
        "Idaho Falls, ID",
        "Jerome, ID",
        "Lewiston, ID",
        "Meridian, ID",
        "Moscow, ID",
        "Mountain Home, ID",
        "Nampa, ID",
        "Pocatello, ID",
        "Rexburg, ID",
        "Twin Falls, ID",
    ],
    "Illinois": [
        "Algonquin, IL",
        "Aurora, IL",
        "Bloomington, IL",
        "Bolingbrook, IL",
        "Buffalo Grove, IL",
        "Carol Stream, IL",
        "Champaign, IL",
        "Chicago, IL",
        "Cicero, IL",
        "Crystal Lake, IL",
        "Decatur, IL",
        "Des Plaines, IL",
        "Elgin, IL",
        "Evanston, IL",
        "Glenview, IL",
        "Joliet, IL",
        "Lisle, IL",
        "Lombard, IL",
        "Moline, IL",
        "Naperville, IL",
        "Normal, IL",
        "Oak Lawn, IL",
        "Oak Park, IL",
        "Orland Park, IL",
        "Palatine, IL",
        "Peoria, IL",
        "Rockford, IL",
        "Schaumburg, IL",
        "Skokie, IL",
        "Springfield, IL",
        "Tinley Park, IL",
        "Waukegan, IL",
        "Wheaton, IL",
    ],
    "Indiana": [
        "Anderson, IN",
        "Bloomington, IN",
        "Carmel, IN",
        "Columbus, IN",
        "Crown Point, IN",
        "Evansville, IN",
        "Fishers, IN",
        "Fort Wayne, IN",
        "Gary, IN",
        "Greenfield, IN",
        "Greenwood, IN",
        "Hammond, IN",
        "Indianapolis, IN",
        "Jeffersonville, IN",
        "Kokomo, IN",
        "Lafayette, IN",
        "Lawrence, IN",
        "Muncie, IN",
        "Noblesville, IN",
        "Richmond, IN",
        "South Bend, IN",
        "Terre Haute, IN",
        "Valparaiso, IN",
    ],
    "Iowa": [
        "Ames, IA",
        "Ankeny, IA",
        "Bettendorf, IA",
        "Burlington, IA",
        "Cedar Falls, IA",
        "Cedar Rapids, IA",
        "Clinton, IA",
        "Council Bluffs, IA",
        "Davenport, IA",
        "Des Moines, IA",
        "Dubuque, IA",
        "Fort Dodge, IA",
        "Iowa City, IA",
        "Marshalltown, IA",
        "Mason City, IA",
        "Muscatine, IA",
        "Sioux City, IA",
        "Urbandale, IA",
        "Waterloo, IA",
        "West Des Moines, IA",
    ],
    "Kansas": [
        "Arkansas City, KS",
        "Atchison, KS",
        "Emporia, KS",
        "Garden City, KS",
        "Hays, KS",
        "Hutchinson, KS",
        "Independence, KS",
        "Kansas City, KS",
        "Lawrence, KS",
        "Leavenworth, KS",
        "Lenexa, KS",
        "Manhattan, KS",
        "Olathe, KS",
        "Overland Park, KS",
        "Pittsburg, KS",
        "Salina, KS",
        "Shawnee, KS",
        "Topeka, KS",
        "Wichita, KS",
    ],
    "Kentucky": [
        "Ashland, KY",
        "Bowling Green, KY",
        "Covington, KY",
        "Danville, KY",
        "Elizabethtown, KY",
        "Florence, KY",
        "Frankfort, KY",
        "Georgetown, KY",
        "Henderson, KY",
        "Hopkinsville, KY",
        "Lexington, KY",
        "Louisville, KY",
        "Murray, KY",
        "Nicholasville, KY",
        "Owensboro, KY",
        "Paducah, KY",
        "Richmond, KY",
        "Somerset, KY",
    ],
    "Louisiana": [
        "Alexandria, LA",
        "Baton Rouge, LA",
        "Bossier City, LA",
        "Central, LA",
        "Covington, LA",
        "Hammond, LA",
        "Houma, LA",
        "Kenner, LA",
        "Lafayette, LA",
        "Lake Charles, LA",
        "Mandeville, LA",
        "Monroe, LA",
        "Natchitoches, LA",
        "New Iberia, LA",
        "New Orleans, LA",
        "Opelousas, LA",
        "Ruston, LA",
        "Shreveport, LA",
        "Slidell, LA",
        "Sulphur, LA",
        "Thibodaux, LA",
    ],
    "Maine": [
        "Augusta, ME",
        "Bangor, ME",
        "Biddeford, ME",
        "Brunswick, ME",
        "Lewiston, ME",
        "Portland, ME",
        "Saco, ME",
        "Sanford, ME",
        "South Portland, ME",
        "Westbrook, ME",
    ],
    "Maryland": [
        "Annapolis, MD",
        "Baltimore, MD",
        "Bel Air, MD",
        "Bethesda, MD",
        "Bowie, MD",
        "College Park, MD",
        "Columbia, MD",
        "Dundalk, MD",
        "Elkton, MD",
        "Frederick, MD",
        "Gaithersburg, MD",
        "Germantown, MD",
        "Glen Burnie, MD",
        "Hagerstown, MD",
        "Laurel, MD",
        "Rockville, MD",
        "Salisbury, MD",
        "Silver Spring, MD",
        "Towson, MD",
        "Waldorf, MD",
    ],
    "Massachusetts": [
        "Boston, MA",
        "Brockton, MA",
        "Cambridge, MA",
        "Chicopee, MA",
        "Fall River, MA",
        "Fitchburg, MA",
        "Framingham, MA",
        "Haverhill, MA",
        "Holyoke, MA",
        "Lawrence, MA",
        "Lowell, MA",
        "Lynn, MA",
        "Malden, MA",
        "Medford, MA",
        "New Bedford, MA",
        "Newton, MA",
        "Peabody, MA",
        "Pittsfield, MA",
        "Quincy, MA",
        "Revere, MA",
        "Somerville, MA",
        "Springfield, MA",
        "Taunton, MA",
        "Waltham, MA",
        "Weymouth, MA",
        "Worcester, MA",
    ],
    "Michigan": [
        "Ann Arbor, MI",
        "Battle Creek, MI",
        "Bay City, MI",
        "Dearborn, MI",
        "Dearborn Heights, MI",
        "Detroit, MI",
        "Farmington Hills, MI",
        "Flint, MI",
        "Grand Rapids, MI",
        "Holland, MI",
        "Jackson, MI",
        "Kalamazoo, MI",
        "Lansing, MI",
        "Livonia, MI",
        "Midland, MI",
        "Monroe, MI",
        "Mount Pleasant, MI",
        "Muskegon, MI",
        "Novi, MI",
        "Pontiac, MI",
        "Port Huron, MI",
        "Rochester Hills, MI",
        "Royal Oak, MI",
        "Saginaw, MI",
        "Southfield, MI",
        "Sterling Heights, MI",
        "Taylor, MI",
        "Troy, MI",
        "Warren, MI",
        "Westland, MI",
        "Wyoming, MI",
        "Ypsilanti, MI",
    ],
    "Minnesota": [
        "Andover, MN",
        "Apple Valley, MN",
        "Blaine, MN",
        "Bloomington, MN",
        "Brooklyn Park, MN",
        "Burnsville, MN",
        "Coon Rapids, MN",
        "Duluth, MN",
        "Eagan, MN",
        "Eden Prairie, MN",
        "Edina, MN",
        "Lakeville, MN",
        "Maple Grove, MN",
        "Minneapolis, MN",
        "Minnetonka, MN",
        "Moorhead, MN",
        "Plymouth, MN",
        "Rochester, MN",
        "Roseville, MN",
        "St. Cloud, MN",
        "St. Louis Park, MN",
        "St. Paul, MN",
        "Woodbury, MN",
    ],
    "Mississippi": [
        "Biloxi, MS",
        "Brandon, MS",
        "Clarksdale, MS",
        "Clinton, MS",
        "Columbus, MS",
        "Gautier, MS",
        "Greenville, MS",
        "Gulfport, MS",
        "Hattiesburg, MS",
        "Horn Lake, MS",
        "Jackson, MS",
        "Laurel, MS",
        "Long Beach, MS",
        "Madison, MS",
        "McComb, MS",
        "Meridian, MS",
        "Natchez, MS",
        "Ocean Springs, MS",
        "Olive Branch, MS",
        "Oxford, MS",
        "Pascagoula, MS",
        "Pearl, MS",
        "Ridgeland, MS",
        "Southaven, MS",
        "Starkville, MS",
        "Tupelo, MS",
        "Vicksburg, MS",
    ],
    "Missouri": [
        "Blue Springs, MO",
        "Cape Girardeau, MO",
        "Chesterfield, MO",
        "Columbia, MO",
        "Florissant, MO",
        "Gladstone, MO",
        "Independence, MO",
        "Jefferson City, MO",
        "Joplin, MO",
        "Kansas City, MO",
        "Lee's Summit, MO",
        "Liberty, MO",
        "Maryland Heights, MO",
        "O'Fallon, MO",
        "Raytown, MO",
        "Saint Charles, MO",
        "Saint Joseph, MO",
        "Saint Louis, MO",
        "Springfield, MO",
        "St. Peters, MO",
    ],
    "Montana": [
        "Anaconda, MT",
        "Billings, MT",
        "Bozeman, MT",
        "Butte, MT",
        "Great Falls, MT",
        "Helena, MT",
        "Kalispell, MT",
        "Missoula, MT",
        "Miles City, MT",
        "Whitefish, MT",
    ],
    "Nebraska": [
        "Bellevue, NE",
        "Columbus, NE",
        "Fremont, NE",
        "Grand Island, NE",
        "Hastings, NE",
        "Kearney, NE",
        "Lincoln, NE",
        "Norfolk, NE",
        "North Platte, NE",
        "Omaha, NE",
        "Papillion, NE",
        "Scottsbluff, NE",
    ],
    "Nevada": [
        "Boulder City, NV",
        "Carson City, NV",
        "Elko, NV",
        "Enterprise, NV",
        "Henderson, NV",
        "Las Vegas, NV",
        "Mesquite, NV",
        "North Las Vegas, NV",
        "Pahrump, NV",
        "Reno, NV",
        "Sparks, NV",
        "Summerlin South, NV",
        "Whitney, NV",
    ],
    "New Hampshire": [
        "Bedford, NH",
        "Concord, NH",
        "Derry, NH",
        "Dover, NH",
        "Keene, NH",
        "Laconia, NH",
        "Manchester, NH",
        "Merrimack, NH",
        "Nashua, NH",
        "Portsmouth, NH",
        "Rochester, NH",
        "Salem, NH",
    ],
    "New Jersey": [
        "Atlantic City, NJ",
        "Bayonne, NJ",
        "Belleville, NJ",
        "Bergenfield, NJ",
        "Bloomfield, NJ",
        "Brick, NJ",
        "Camden, NJ",
        "Clifton, NJ",
        "East Brunswick, NJ",
        "Edison, NJ",
        "Elizabeth, NJ",
        "Englewood, NJ",
        "Fort Lee, NJ",
        "Garfield, NJ",
        "Hackensack, NJ",
        "Hoboken, NJ",
        "Jersey City, NJ",
        "Kearny, NJ",
        "Lakewood, NJ",
        "Linden, NJ",
        "New Brunswick, NJ",
        "Newark, NJ",
        "North Bergen, NJ",
        "Passaic, NJ",
        "Paterson, NJ",
        "Perth Amboy, NJ",
        "Plainfield, NJ",
        "Princeton, NJ",
        "Sayreville, NJ",
        "Trenton, NJ",
        "Union City, NJ",
        "Wayne, NJ",
        "West New York, NJ",
        "Woodbridge, NJ",
    ],
    "New Mexico": [
        "Alamogordo, NM",
        "Albuquerque, NM",
        "Artesia, NM",
        "Carlsbad, NM",
        "Clovis, NM",
        "Farmington, NM",
        "Gallup, NM",
        "Hobbs, NM",
        "Las Cruces, NM",
        "Las Vegas, NM",
        "Los Alamos, NM",
        "Roswell, NM",
        "Santa Fe, NM",
        "Silver City, NM",
        "Taos, NM",
    ],
    "New York": [
        "Albany, NY",
        "Amsterdam, NY",
        "Auburn, NY",
        "Babylon, NY",
        "Batavia, NY",
        "Binghamton, NY",
        "Buffalo, NY",
        "Cortland, NY",
        "Elmira, NY",
        "Freeport, NY",
        "Garden City, NY",
        "Glens Falls, NY",
        "Hempstead, NY",
        "Ithaca, NY",
        "Jamestown, NY",
        "Kingston, NY",
        "Lackawanna, NY",
        "Long Beach, NY",
        "Middletown, NY",
        "Mount Vernon, NY",
        "New Rochelle, NY",
        "New York, NY",
        "Niagara Falls, NY",
        "Olean, NY",
        "Peekskill, NY",
        "Poughkeepsie, NY",
        "Rochester, NY",
        "Rome, NY",
        "Saratoga Springs, NY",
        "Schenectady, NY",
        "Syracuse, NY",
        "Troy, NY",
        "Utica, NY",
        "Watertown, NY",
        "White Plains, NY",
        "Yonkers, NY",
    ],
    "North Carolina": [
        "Asheville, NC",
        "Burlington, NC",
        "Cary, NC",
        "Chapel Hill, NC",
        "Charlotte, NC",
        "Concord, NC",
        "Durham, NC",
        "Fayetteville, NC",
        "Gastonia, NC",
        "Greensboro, NC",
        "Greenville, NC",
        "Hickory, NC",
        "High Point, NC",
        "Jacksonville, NC",
        "Kannapolis, NC",
        "Raleigh, NC",
        "Rocky Mount, NC",
        "Salisbury, NC",
        "Sanford, NC",
        "Wilmington, NC",
        "Wilson, NC",
        "Winston-Salem, NC",
    ],
    "North Dakota": [
        "Bismarck, ND",
        "Dickinson, ND",
        "Fargo, ND",
        "Grand Forks, ND",
        "Jamestown, ND",
        "Mandan, ND",
        "Minot, ND",
        "Williston, ND",
    ],
    "Ohio": [
        "Akron, OH",
        "Alliance, OH",
        "Ashland, OH",
        "Athens, OH",
        "Avon Lake, OH",
        "Barberton, OH",
        "Beavercreek, OH",
        "Bowling Green, OH",
        "Canton, OH",
        "Cincinnati, OH",
        "Cleveland, OH",
        "Cleveland Heights, OH",
        "Columbus, OH",
        "Cuyahoga Falls, OH",
        "Dublin, OH",
        "Euclid, OH",
        "Fairborn, OH",
        "Findlay, OH",
        "Gahanna, OH",
        "Hamilton, OH",
        "Kettering, OH",
        "Lakewood, OH",
        "Lancaster, OH",
        "Lima, OH",
        "Lorain, OH",
        "Mansfield, OH",
        "Marietta, OH",
        "Mason, OH",
        "Middletown, OH",
        "Newark, OH",
        "Parma, OH",
        "Reynoldsburg, OH",
        "Springfield, OH",
        "Toledo, OH",
        "Upper Arlington, OH",
        "Westerville, OH",
        "Westlake, OH",
        "Wooster, OH",
        "Youngstown, OH",
    ],
    "Oklahoma": [
        "Altus, OK",
        "Ardmore, OK",
        "Bartlesville, OK",
        "Broken Arrow, OK",
        "Claremore, OK",
        "Duncan, OK",
        "Edmond, OK",
        "Enid, OK",
        "Lawton, OK",
        "McAlester, OK",
        "Midwest City, OK",
        "Muskogee, OK",
        "Norman, OK",
        "Oklahoma City, OK",
        "Owasso, OK",
        "Ponca City, OK",
        "Stillwater, OK",
        "Tulsa, OK",
    ],
    "Oregon": [
        "Albany, OR",
        "Ashland, OR",
        "Beaverton, OR",
        "Bend, OR",
        "Corvallis, OR",
        "Eugene, OR",
        "Grants Pass, OR",
        "Gresham, OR",
        "Hillsboro, OR",
        "Klamath Falls, OR",
        "Lake Oswego, OR",
        "Medford, OR",
        "Milwaukie, OR",
        "Oregon City, OR",
        "Portland, OR",
        "Redmond, OR",
        "Salem, OR",
        "Springfield, OR",
        "Tigard, OR",
        "Tualatin, OR",
        "West Linn, OR",
        "Wilsonville, OR",
    ],
    "Pennsylvania": [
        "Allentown, PA",
        "Altoona, PA",
        "Bethlehem, PA",
        "Butler, PA",
        "Chambersburg, PA",
        "Chester, PA",
        "Easton, PA",
        "Erie, PA",
        "Greensburg, PA",
        "Harrisburg, PA",
        "Hazleton, PA",
        "Johnstown, PA",
        "Lancaster, PA",
        "Lebanon, PA",
        "McKeesport, PA",
        "Monroeville, PA",
        "Norristown, PA",
        "Philadelphia, PA",
        "Pittsburgh, PA",
        "Reading, PA",
        "Scranton, PA",
        "State College, PA",
        "Upper Darby, PA",
        "Wilkes-Barre, PA",
        "Williamsport, PA",
        "York, PA",
    ],
    "Rhode Island": [
        "Bristol, RI",
        "Central Falls, RI",
        "Cranston, RI",
        "East Providence, RI",
        "Newport, RI",
        "Pawtucket, RI",
        "Providence, RI",
        "Warwick, RI",
        "Westerly, RI",
        "Woonsocket, RI",
    ],
    "South Carolina": [
        "Aiken, SC",
        "Anderson, SC",
        "Beaufort, SC",
        "Charleston, SC",
        "Columbia, SC",
        "Conway, SC",
        "Florence, SC",
        "Goose Creek, SC",
        "Greenville, SC",
        "Greer, SC",
        "Hilton Head Island, SC",
        "Mount Pleasant, SC",
        "Myrtle Beach, SC",
        "North Charleston, SC",
        "Rock Hill, SC",
        "Spartanburg, SC",
        "Summerville, SC",
        "Sumter, SC",
    ],
    "South Dakota": [
        "Aberdeen, SD",
        "Brookings, SD",
        "Huron, SD",
        "Mitchell, SD",
        "Pierre, SD",
        "Rapid City, SD",
        "Sioux Falls, SD",
        "Spearfish, SD",
        "Watertown, SD",
        "Yankton, SD",
    ],
    "Tennessee": [
        "Bartlett, TN",
        "Brentwood, TN",
        "Bristol, TN",
        "Chattanooga, TN",
        "Clarksville, TN",
        "Cleveland, TN",
        "Collierville, TN",
        "Cookeville, TN",
        "Franklin, TN",
        "Germantown, TN",
        "Hendersonville, TN",
        "Jackson, TN",
        "Johnson City, TN",
        "Kingsport, TN",
        "Knoxville, TN",
        "La Vergne, TN",
        "Lebanon, TN",
        "Maryville, TN",
        "Memphis, TN",
        "Murfreesboro, TN",
        "Nashville, TN",
        "Oak Ridge, TN",
        "Smyrna, TN",
        "Spring Hill, TN",
    ],
    "Texas": [
        "Abilene, TX",
        "Allen, TX",
        "Amarillo, TX",
        "Arlington, TX",
        "Austin, TX",
        "Baytown, TX",
        "Beaumont, TX",
        "Brownsville, TX",
        "Bryan, TX",
        "Carrollton, TX",
        "Cedar Park, TX",
        "College Station, TX",
        "Conroe, TX",
        "Corpus Christi, TX",
        "Dallas, TX",
        "Denton, TX",
        "Edinburg, TX",
        "El Paso, TX",
        "Flower Mound, TX",
        "Fort Worth, TX",
        "Frisco, TX",
        "Galveston, TX",
        "Garland, TX",
        "Georgetown, TX",
        "Grand Prairie, TX",
        "Grapevine, TX",
        "Harlingen, TX",
        "Houston, TX",
        "Humble, TX",
        "Irving, TX",
        "Katy, TX",
        "Killeen, TX",
        "League City, TX",
        "Lewisville, TX",
        "Longview, TX",
        "Lubbock, TX",
        "McAllen, TX",
        "McKinney, TX",
        "Mesquite, TX",
        "Midland, TX",
        "Missouri City, TX",
        "New Braunfels, TX",
        "Odessa, TX",
        "Pasadena, TX",
        "Pearland, TX",
        "Pflugerville, TX",
        "Plano, TX",
        "Port Arthur, TX",
        "Richardson, TX",
        "Round Rock, TX",
        "San Angelo, TX",
        "San Antonio, TX",
        "San Marcos, TX",
        "Schertz, TX",
        "Sherman, TX",
        "Sugar Land, TX",
        "Temple, TX",
        "The Woodlands, TX",
        "Tyler, TX",
        "Victoria, TX",
        "Waco, TX",
        "Wichita Falls, TX",
    ],
    "Utah": [
        "American Fork, UT",
        "Bountiful, UT",
        "Brigham City, UT",
        "Cedar City, UT",
        "Clearfield, UT",
        "Draper, UT",
        "Eagle Mountain, UT",
        "Herriman, UT",
        "Kaysville, UT",
        "Layton, UT",
        "Lehi, UT",
        "Logan, UT",
        "Midvale, UT",
        "Murray, UT",
        "Ogden, UT",
        "Orem, UT",
        "Park City, UT",
        "Pleasant Grove, UT",
        "Provo, UT",
        "Riverton, UT",
        "Roy, UT",
        "Salt Lake City, UT",
        "Sandy, UT",
        "Saratoga Springs, UT",
        "South Jordan, UT",
        "Spanish Fork, UT",
        "Springville, UT",
        "St. George, UT",
        "Taylorsville, UT",
        "Tooele, UT",
        "West Jordan, UT",
        "West Valley City, UT",
    ],
    "Vermont": [
        "Barre, VT",
        "Burlington, VT",
        "Essex, VT",
        "Montpelier, VT",
        "Rutland, VT",
        "South Burlington, VT",
        "St. Albans, VT",
        "St. Johnsbury, VT",
        "Winooski, VT",
    ],
    "Virginia": [
        "Alexandria, VA",
        "Arlington, VA",
        "Blacksburg, VA",
        "Bristol, VA",
        "Charlottesville, VA",
        "Chesapeake, VA",
        "Danville, VA",
        "Fairfax, VA",
        "Falls Church, VA",
        "Fredericksburg, VA",
        "Hampton, VA",
        "Harrisonburg, VA",
        "Hopewell, VA",
        "Leesburg, VA",
        "Lynchburg, VA",
        "Manassas, VA",
        "Martinsville, VA",
        "Newport News, VA",
        "Norfolk, VA",
        "Petersburg, VA",
        "Portsmouth, VA",
        "Richmond, VA",
        "Roanoke, VA",
        "Salem, VA",
        "Suffolk, VA",
        "Virginia Beach, VA",
        "Waynesboro, VA",
        "Williamsburg, VA",
        "Winchester, VA",
    ],
    "Washington": [
        "Auburn, WA",
        "Bellevue, WA",
        "Bellingham, WA",
        "Bremerton, WA",
        "Everett, WA",
        "Federal Way, WA",
        "Issaquah, WA",
        "Kennewick, WA",
        "Kirkland, WA",
        "Lacey, WA",
        "Lakewood, WA",
        "Longview, WA",
        "Marysville, WA",
        "Olympia, WA",
        "Pasco, WA",
        "Pullman, WA",
        "Puyallup, WA",
        "Redmond, WA",
        "Renton, WA",
        "Richland, WA",
        "Seattle, WA",
        "Shoreline, WA",
        "Spokane, WA",
        "Tacoma, WA",
        "Vancouver, WA",
        "Walla Walla, WA",
        "Wenatchee, WA",
        "Yakima, WA",
    ],
    "West Virginia": [
        "Beckley, WV",
        "Bluefield, WV",
        "Bridgeport, WV",
        "Charleston, WV",
        "Clarksburg, WV",
        "Fairmont, WV",
        "Huntington, WV",
        "Martinsburg, WV",
        "Morgantown, WV",
        "Parkersburg, WV",
        "South Charleston, WV",
        "Wheeling, WV",
    ],
    "Wisconsin": [
        "Appleton, WI",
        "Beloit, WI",
        "Brookfield, WI",
        "Eau Claire, WI",
        "Fond du Lac, WI",
        "Green Bay, WI",
        "Janesville, WI",
        "Kenosha, WI",
        "La Crosse, WI",
        "Madison, WI",
        "Manitowoc, WI",
        "Marshfield, WI",
        "Menasha, WI",
        "Milwaukee, WI",
        "Neenah, WI",
        "Oshkosh, WI",
        "Racine, WI",
        "Sheboygan, WI",
        "Stevens Point, WI",
        "Sun Prairie, WI",
        "Waukesha, WI",
        "Wausau, WI",
        "West Allis, WI",
        "Wisconsin Rapids, WI",
    ],
    "Wyoming": [
        "Casper, WY",
        "Cheyenne, WY",
        "Cody, WY",
        "Evanston, WY",
        "Gillette, WY",
        "Green River, WY",
        "Jackson, WY",
        "Laramie, WY",
        "Rock Springs, WY",
        "Sheridan, WY",
    ],
}

STATE_ABBR = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

ALL_STATES = sorted(STATE_CITIES.keys())


def cities_for_state(state_name):
    """Returns the sorted list of "City, ST" strings for a given full
    state name, or an empty list if the state isn't recognized.
    """
    return STATE_CITIES.get(state_name, [])
